GSI-CS-CO/bel_projects

- tools/eb-console.c
- tools/eb-flash.c
- tools/eb-info.c
In case commit is accepted and merged into balloon, please close issue https://github.com/GSI-CS-CO/bel_projects/issues/13.
> tools: fixing minor issues in command line help for some eb tools

- Makefile
- Manifest.py
- install-hdlmake.sh
- modules/ddr3/Manifest.py
- syn/build.mk
- syn/gsi_addac/Makefile
- syn/gsi_addac/Manifest.py
- syn/gsi_addac2/Makefile
- syn/gsi_addac2/Manifest.py
- syn/gsi_ifa8/Manifest.py
- syn/scu_diob/Makefile
- syn/scu_diob/Manifest.py
- syn/scu_sio3/Makefile
- syn/scu_sio3/Manifest.py
- top/gsi_ifa8/Manifest.py
merge changes for the new version hdlmake3
please run the following commands for testing
```
$ cd ip_cores/hdlmake/
$ git checkout develop
$ cd ../../
$ ./install-hdlmake.sh
```
> Hdlmake3 migration

- tools/Makefile
- tools/eb-reset.c
- tools/wb_api.c
- tools/wb_api.h
- tools/wb_slaves.h
Hi Alex, just in case you are interested to include this...
> eb-reset: add eb tool 'eb-reset'.

- tools/demo-and-test/Makefile
- tools/demo-and-test/eb_native_demo.c
- tools/demo-and-test/eb_perf_demo.c
- tools/demo-and-test/eb_tlu_demo.c
- tools/demo-and-test/readme.txt
- tools/wb_slaves.h
> Test demo dietrich 2018 02 07

- modules/dm-unipz/Makefile
- modules/dm-unipz/dmunipz-asl/dmunipz.sh
- modules/dm-unipz/dmunipz-fw/Makefile
- modules/dm-unipz/dmunipz-fw/dm-unipz.c
- modules/dm-unipz/dmunipz-fw/dm-unipz.gv
- modules/dm-unipz/dmunipz-fw/dm-unipz.h
- modules/dm-unipz/dmunipz-x86/Makefile
- modules/dm-unipz/dmunipz-x86/dm-unipz_start.sh
- modules/dm-unipz/dmunipz-x86/dmunipz-ctl.c
- modules/ftm/ftmx86/Makefile
I accidentally committed "../modules/ftm/ftmx86/Makefile" in commit 9c57d57. This is creating a conflict that can be resolved by keeping the actual version of branch dm-dev-190218
> Dm unipz dietrich 2018 mar 06

- tools/monitoring/.gitignore
- tools/monitoring/Makefile
- tools/monitoring/eb-massmon.c
- tools/monitoring/eb-mon.c
- tools/wb_api.c
- tools/wb_api.h
- tools/wb_slaves.h
> Eb reset dietrich 2018 apr 20

- syn/scu_sio3/scu_sio3.tcl
fixes missing tcl source for sio3
> sio3: generate clk region cores

- syn/gsi_ifa8/ifa8.qsf
- top/gsi_ifa8/ifactl.vhd
- top/gsi_ifa8/ifpar_a.bdf
These commits shoud be in doomsday.
> Ifa8 status read

- tools/monitoring/eb-massmon.c
- tools/monitoring/eb-mon.c
- tools/wb_api.c
- tools/wb_api.h
- tools/wb_slaves.h
extended eb-mon and eb-massmon
open issue https://github.com/GSI-CS-CO/bel_projects/issues/103 fixed by software
> Doomsday eb-tools: adding 'WR lock' statistics acquired from DM_Diagnosics module

- modules/monster/monster.dot
> monster: adding hand-made graph for wb x-bar layout

- top/gsi_scu/main.c
> Doomsday v4.0.6

- .travis.yml
Builds and installs saftlib after succeeding to build bel_projects.
> Travis saftlib build

- .travis.yml
wrpc-sw can be built by travis
> travis: added firmware build (lm32 toolchain, wrpc-sw)

- .gitmodules
- fix-git.sh
> submodules: updated OHWR paths

- modules/monster/monster.vhd
- modules/monster/monster_pkg.vhd
- modules/wb_arria_reset/wb_arria_reset.vhd
- modules/wb_arria_reset/wb_arria_reset_pkg.vhd
- tools/eb-reset.c
- tools/wb_api.c
- tools/wb_api.h
- tools/wb_slaves.h
- top/gsi_scu/control2/scu_control.vhd
- top/gsi_scu/control3/scu_control.vhd
> Watchdog dietrich 2019 mar 01

- modules/monster/monster.vhd
- modules/monster/monster_pkg.vhd
- modules/wb_arria_reset/wb_arria_reset.vhd
- modules/wb_arria_reset/wb_arria_reset_pkg.vhd
- tools/eb-reset.c
- tools/wb_api.c
- tools/wb_api.h
- tools/wb_slaves.h
- top/gsi_scu/control2/scu_control.vhd
- top/gsi_scu/control3/scu_control.vhd
enabled for SCUs only
needs to be reset once within 10min after powerup, otherwise the watchdog restarts the FPGA
reset is done by:` eb-reset <etherbone-device> wddisable`
> Watchdog, again

- modules/b2b-test/b2btest-fw/Makefile
- modules/b2b-test/b2btest-fw/b2b-cbu.c
- modules/b2b-test/b2btest-fw/b2b-common.c
- modules/b2b-test/b2btest-fw/b2b-pm.c
- modules/b2b-test/b2btest-x86/b2btest-api.c
- modules/b2b-test/b2btest-x86/b2btest-ctl.c
- modules/b2b-test/ftrn-cbu.sh
- modules/b2b-test/ftrn-tlu.sh
- modules/b2b-test/include/b2b-common.h
- modules/b2b-test/include/b2b-test.h
- modules/b2b-test/include/b2btest-api.h
- modules/lm32-include/mini_sdb.c
- modules/lm32-include/stack-check.c
- modules/wr-unipz/wrunipz-fw/wr-unipz.c
first proof-of-principle phase matching of two h=1 signals using frequency beats
> B2b test dietrich 2019 05 20

- tools/eb-flash-secure
tools/eb-flash-secure -> initial version
@dietrichb @stefanrauch : Feel free to modify the script.
> eb-flash-secure: initial

- Makefile
- syn/gsi_exploder5/exploder5_csco_tr/exploder5_csco_tr.qsf
- syn/gsi_microtca/control/microtca_control.qsf
- syn/gsi_pexarria5/control/pci_control.qsf
- syn/gsi_pexarria5/ftm/ftm.qsf
- syn/gsi_pmc/control/pci_pmc.qsf
- syn/gsi_scu/control2/scu_control.qsf
- syn/gsi_scu/control3/scu_control.qsf
- syn/gsi_vetar2a/ee_butis/vetar2a.qsf
- syn/gsi_vetar2a/wr_core_demo/vetar2a.qsf
> Makefile: added an option to sort qsf files - make target-sort

- tools/monitoring/allTimingDevices.txt
- tools/monitoring/eb-mon.c
fixed a bug and a few minor issues
> Ebmon dietrich 2019 oct 15

- modules/Manifest.py
- modules/dac714/dac714.vhd
- modules/dac714/dac714_pkg.vhd
- modules/daq/Manifest.py
- modules/daq/Zeitbasis_daq.vhd
- modules/daq/crc5x16.vhd
- modules/daq/daq.vhd
- modules/daq/daq_chan_reg_logic.vhd
- modules/daq/daq_pkg.vhd
- top/gsi_addac2/scu_addac.vhd
> Daq for addac2 rebased

- top/scu_diob/scu_diob.vhd
> Diob puls fix

- modules/aux_functions/slave_clk_switch.vhd
- top/gsi_scu/fg.c
fixes clk switch of diob slave cards after eb-reset of SCU
> scu_sw and slave_clk_switch: fix diob switching

- modules/lm32-include/build_lm32.mk
This addresses the problem Martin Skorsky initially attacked with pull request #208, that he
later retired.
Martin already reviewed the commits and approved them (I just edited typos in commit message).
> Minor build fixes

- top/scu_diob/Manifest.py
- top/scu_diob/atr_cnt_n.vhd
- top/scu_diob/atr_comp_ctrl.vhd
- top/scu_diob/atr_puls_ctrl.vhd
- top/scu_diob/atr_puls_n.vhd
- top/scu_diob/atr_timeout.vhd
- top/scu_diob/io_spi_dac_8420.vhd
- top/scu_diob/scu_diob.vhd
- top/scu_diob/tag_ctrl.vhd
- top/scu_diob/tag_n.vhd
Reintegration of K. Kaiser changes for ATR.
Feature tested by Ulf Reinhardt
> Diob atr reintegration

- modules/lm32-include/aux.h
fixes https://github.com/GSI-CS-CO/bel_projects/issues/236
> aux.h: fixed uSleep

- modules/lm32-example/timerExample.c
- modules/wb_timer/wb_timer_regs.h
> Lm32 dietrich 2020 may 20

- modules/ftm/ftmx86/Makefile
- modules/ftm/include/dotstr.h
- modules/ftm/include/graph.h
- modules/ftm/src/carpeDMimpl.cpp
- modules/ftm/src/dotstr.cpp
- modules/ftm/src/graph.cpp
- modules/ftm/src/idformat.cpp
- modules/prioq2/prio.vhd
Implementation for the flag Beamprocess Chain start. Using bit 34 of timing message id: 1 means start of Beamprocess Chain. Implementation in libcarpedm.so
> Flag bpc start

- modules/lm32-example/Makefile
- modules/lm32-example/miniExample.c
- modules/lm32-example/timerExample.c
- modules/lm32-include/aux.c
- modules/lm32-include/aux.h
- modules/lm32-include/mini_sdb.c
- modules/lm32-include/mini_sdb.h
- modules/wb_timer/wb_timer_regs.h
pull request with tested and latest
- timer example (lm32-examples)
- uwait (lm32-include -> aux)
this requires a fix for the timer HDL (probably via another pull request)
> Lm32 dietrich 2020 june 04

- modules/common-libs/fw/common-fwlib.c
- modules/common-libs/fw/example.c
- modules/wr-unipz/fw/Makefile
- modules/wr-unipz/fw/wr-unipz.c
- modules/wr-unipz/include/wr-unipz.h
- modules/wr-unipz/include/wrunipzlib.h
- modules/wr-unipz/x86/wrunipz-ctl.c
- top/gsi_scu/scu_mil.c
- x86: CLI to new data format of DeviceAccess eqmodel/pz
- fw: included service event for Alvarez 4
- fw, scu_mil: using new timer (usleep -> uwait)
- 1st port to fallout
> Wr unipz dietrich 2020 aug 12

- top/gsi_scu/main.c
this change will need a small adaption in saftlib too
> scu_sw: new memory position for rescan busy flag

- tools/monitoring/eb-massmon.c
> Ebmon dietrich 2020 sep 17

- syn/gsi_scu/control2/Makefile
- syn/gsi_scu/control3/Makefile
- top/gsi_scu/main.c
make stack check visible in eb-info
> scu_sw: enable check_stack_fwid

- modules/monster/monster.vhd
- To be tested (lock, data loss, ...)
- Seed mining (all Arria V devices)
> monster: changed phy tx clk (arria5)

- top/gsi_addac/scu_addac.vhd
add daq macro to ADDAC1 SCU bus slave
> gsi_addac: add daq macro

- syn/gsi_exploder5/exploder5_csco_tr/exploder5_csco_tr.qsf
- syn/gsi_microtca/control/microtca_control.qsf
- syn/gsi_pexarria5/control/pci_control.qsf
- syn/gsi_pexp/control/pexp_control.qsf
- syn/gsi_pmc/control/pci_pmc.qsf
Patch for unstable clock generator/LVDS serdes.
Needs to be tested on all ArriaV-based devices.
> Fallout clk ll test

- tools/monitoring/eb-massmon.c
> eb-massmon: changed from allTimingDevices.txt to ipam format

- modules/fec-analyzer/x86/Makefile
- modules/fec-analyzer/x86/fec-analyzer.cpp
- tools/demo-and-test/Makefile
- tools/demo-and-test/eb_read_time.c
- fec timing receiver delivery measurement
- very basic example for reading WR time
> Fec analyzer dietrich 2021 feb 11

- modules/monster/monster.vhd
- modules/monster/monster_pkg.vhd
- modules/wb_arria_reset/wb_arria_reset.vhd
- modules/wb_arria_reset/wb_arria_reset_pkg.vhd
- top/gsi_exploder5/exploder5_csco_tr/exploder5_csco_tr.vhd
- top/gsi_microtca/control/microtca_control.vhd
- top/gsi_pexarria5/control/pci_control.vhd
- top/gsi_pexarria5/ftm/ftm.vhd
- top/gsi_pexp/control/pexp_control.vhd
- top/gsi_pmc/control/pci_pmc.vhd
- top/gsi_scu/control2/scu_control.vhd
- top/gsi_scu/control3/scu_control.vhd
- top/gsi_vetar2a/ee_butis/vetar2a_ee_butis.vhd
- top/gsi_vetar2a/wr_core_demo/vetar2a_top.vhd
ToDo:
- Seed mining
- eb-reset extension
> Fallout phy reset

- modules/dm-unipz/fw/Makefile
- modules/dm-unipz/fw/dm-unipz.c
dm-unipz ported to 6.0.2 due to changes in .../modules/common-libs
> dm-unipz: ported to fallout 6.0.2

- modules/common-libs/include/common-defs.h
- modules/common-libs/include/common-fwlib.h
- modules/wr-unipz/fw/Makefile
- modules/wr-unipz/fw/wr-unipz.c
ported wrunipz to fallout 6.0.2
> Wrunipz dietrich 2021 jun 23

- modules/wr-unipz/fw/Makefile
- modules/wr-unipz/fw/wr-unipz.c
- modules/wr-unipz/include/wrunipzlib.h
rolled out to production on 3 September 2021
> wr-unipz: ported to fallout 6.1.2

- modules/wr-unipz/fw/Makefile
- modules/wr-unipz/fw/wr-unipz.c
firmware updated to latest changes in 'fallout'
> wr-unipz: port to newer common fwlib

- tools/demo-and-test/Makefile
- tools/demo-and-test/eb_diff_time.c
very simple example for comparing system time and WR time
> eb_diff_time, simple tool for comparing WR time and system time

- modules/wr-unipz/fw/Makefile
- modules/wr-unipz/fw/wr-unipz.c
- modules/wr-unipz/include/wrunipzlib.h
- modules/wr-unipz/x86/wr-unipz_start.sh
- modules/wr-unipz/x86/wrunipz-ctl.c
'White Rabbit Pulszentrale' - here are the fixes that were done during the beamtime 2022
> Wrunipz dietrich 2021 nov 01

- tools/phtif/asl/phtif.sh
merge changes introduced for the 2022 beamtime
> Phtif dietrich 2021 nov 30

- modules/remote_update/Manifest.py
- modules/remote_update/altasmi.cmp
- modules/remote_update/altasmi.qip
- modules/remote_update/altasmi.vhd
- modules/remote_update/remote_update_pkg.vhd
- modules/remote_update/wb_asmi_slave.vhd
- modules/scu_bus/housekeeping.vhd
- modules/wb_scu_reg/wb_scu_reg.vhd
- tools/eb-sflash.c
the merge with the asmi flash controller broke the slave remote update. this is a fix for this problem.
> Fallout slave update fix

- top/scu_diob/Manifest.py
- top/scu_diob/scu_diob.vhd
This is the right DIOB version to be included in fallout
> DIOB: new version of the DIOB top level
